(package "deepl"
         "0.1.0"
         "Elisp library for the DeepL API")

(website-url "https://github.com/emacs-openai/deepl")
(keywords "comm" "deepl")

(package-file "deepl.el")
(files "deepl-*.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'jcs-elpa)
(source 'gnu)
(source 'melpa)

(depends-on "emacs" "26.1")
(depends-on "request")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
